// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUF4kTHYmXfYlz7UxSeD6MJGj9FTiLXRc',
    appId: '1:198955534903:web:21bcc9ed979b2b9b43cdb2',
    messagingSenderId: '198955534903',
    projectId: 'my-menue-app',
    authDomain: 'my-menue-app.firebaseapp.com',
    storageBucket: 'my-menue-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15dVuMQaMZuNz41iK9CO3x82Pd8Q3wAY',
    appId: '1:198955534903:android:43fe3a89dc85632f43cdb2',
    messagingSenderId: '198955534903',
    projectId: 'my-menue-app',
    storageBucket: 'my-menue-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1vWD3yZn_GDbAS2nPW1_r0-WxOWR5VXg',
    appId: '1:198955534903:ios:63bb852fb1b50aa643cdb2',
    messagingSenderId: '198955534903',
    projectId: 'my-menue-app',
    storageBucket: 'my-menue-app.firebasestorage.app',
    iosBundleId: 'com.manoooz.quizProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1vWD3yZn_GDbAS2nPW1_r0-WxOWR5VXg',
    appId: '1:198955534903:ios:63bb852fb1b50aa643cdb2',
    messagingSenderId: '198955534903',
    projectId: 'my-menue-app',
    storageBucket: 'my-menue-app.firebasestorage.app',
    iosBundleId: 'com.manoooz.quizProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUF4kTHYmXfYlz7UxSeD6MJGj9FTiLXRc',
    appId: '1:198955534903:web:0fd6c8c7352c957f43cdb2',
    messagingSenderId: '198955534903',
    projectId: 'my-menue-app',
    authDomain: 'my-menue-app.firebaseapp.com',
    storageBucket: 'my-menue-app.firebasestorage.app',
  );

}